### ISSUE TITLE
Does it include email validation?

### ISSUE THREAD

**Issue by Sathors** [maximeg/email_inquire#2]
It is not really clear from the readme if email_inquire takes care of malformed (invalid) email addresses as well? For example chien@roi@chien.com?

Or do we need another gem for that (for example email_validator)?

Thanks for the nice work though!

**Comment by maximeg** [comment]
No, it currently doesn't include that. But we can add it to be more handy.

It would need some error code to differentiate invalid cases (malformed address, burners...)

I'll cook something in the next days.

**Comment by Sathors** [comment]
Thanks @maximeg. Actually it is pretty useful as-is, even though it would be even nicer if you could add this feature, to avoid having to rely on two different gems for email validation.
